data = [{//U N imamo
    match:{
        id:1,
        code:1234,
        dateTime: "2019-08-14 21:00",
        playground:"Rajko Mitic",
        tip_22:1.5,
        tip_2x:1.5,
        tip_21:1.5,
        tip_x2:1.5,
        tip_xx:1.5,
        tip_x1:1.5,
        tip_12:1.5,
        tip_1x:1.5,
        tip_11:1.5,
        tip2OrMore:1.5,
        tip03:1.5,
        tip01:1.5,
        GG3OrMore:1.5,
        GG:1.5,
        tip4OrMore:1.5,
        tip3OrMore:1.5,
        tip02:1.5,
        tip2OrMoreIP:1.5,
        club_home: "Crvena Zvezda",
        club_away:"Partizan",
        tipAway:1.5,
        tipX:1.5,
        tipHome:1.5,
        id_competition:3,
        id_week:7,
        home_logo:"https://ls.sportradar.com/ls/crest/big/5149.png",
        away_logo:"https://premierleague-static-files.s3.amazonaws.com/premierleague/badges/t216.png"

    },
    competition: {
        id: 3,
        name: 'Prva Srpska Liga',
    },
    week: {
        id: 5,
        name: 'Kolo 3'
    },
    results: null,
    ticket: null
},{//L N
    match:{
        id:1,
        code:1234,
        playground:"Rajko Mitic",
        dateTime: "2019-08-13 15:00",
        tip_22:1.5,
        tip_2x:1.5,
        tip_21:1.5,
        tip_x2:1.5,
        tip_xx:1.5,
        tip_x1:1.5,
        tip_12:1.5,
        tip_1x:1.5,
        tip_11:1.5,
        tip2OrMore:1.5,
        tip03:1.5,
        tip01:1.5,
        GG3OrMore:1.5,
        GG:1.5,
        tip4OrMore:1.5,
        tip3OrMore:1.5,
        tip02:1.5,
        tip2OrMoreIP:1.5,
        club_home: "Crvena Zvezda",
        club_away:"Partizan",
        tipAway:1.5,
        tipX:1.5,
        tipHome:1.5,
        id_competition:3,
        id_week:7,
        home_logo:"https://ls.sportradar.com/ls/crest/big/5149.png",
        away_logo:"https://premierleague-static-files.s3.amazonaws.com/premierleague/badges/t216.png"

    },
    competition: {
        id: 3,
        name: 'Prva Srpska Liga',
    },
    week: {
        id: 5,
        name: 'Kolo 3'
    },
    results: {
        id:5,
        match_id:1,
        tip_22:null,
        tip_2x:null,
        tip_21:null,
        tip_x2:null,
        tip_xx:null,
        tip_x1:null,
        tip_12:null,
        tip_1x:null,
        tip_11:null,
        tip2OrMore:null,
        tip03:null,
        tip01:null,
        GG3OrMore:null,
        GG:null,
        tip4OrMore:null,
        tip3OrMore:null,
        tip02:null,
        tip2OrMoreIP:null,
        tipAway:null,
        tipX:null,
        tipHome:null,
        goals_home:2,
        goals_away:3,
        ht_home:1,
        ht_away:0,
        finished: false,
        current_min: 34,
    },
    ticket: null
},{//L B
    match:{
        id:1,
        code:1234,
        playground:"Rajko Mitic",
        dateTime: "2019-08-13 15:00",
        tip_22:1.5,
        tip_2x:1.5,
        tip_21:1.5,
        tip_x2:1.5,
        tip_xx:1.5,
        tip_x1:1.5,
        tip_12:1.5,
        tip_1x:1.5,
        tip_11:1.5,
        tip2OrMore:1.5,
        tip03:1.5,
        tip01:1.5,
        GG3OrMore:1.5,
        GG:1.5,
        tip4OrMore:1.5,
        tip3OrMore:1.5,
        tip02:1.5,
        tip2OrMoreIP:1.5,
        club_home: "Crvena Zvezda",
        club_away:"Partizan",
        tipAway:1.5,
        tipX:1.5,
        tipHome:1.5,
        id_competition:3,
        id_week:7,
        home_logo:"https://ls.sportradar.com/ls/crest/big/5149.png",
        away_logo:"https://premierleague-static-files.s3.amazonaws.com/premierleague/badges/t216.png"

    },
    competition: {
        id: 3,
        name: 'Prva Srpska Liga',
    },
    week: {
        id: 5,
        name: 'Kolo 3'
    },
    results: {
        id:5,
        match_id:1,
        tip_22:null,
        tip_2x:null,
        tip_21:null,
        tip_x2:null,
        tip_xx:null,
        tip_x1:null,
        tip_12:null,
        tip_1x:null,
        tip_11:null,
        tip2OrMore:null,
        tip03:null,
        tip01:null,
        GG3OrMore:null,
        GG:null,
        tip4OrMore:null,
        tip3OrMore:null,
        tip02:null,
        tip2OrMoreIP:null,
        tipAway:null,
        tipX:null,
        tipHome:null,
        goals_home:2,
        goals_away:3,
        ht_home:1,
        ht_away:0,
        finished: false,
        current_min: 34,
    },
    ticket: {
        id:16,
        user_id:2,
        match_id:1,
        final_score:8,
        bid_score:8,
        final_bid_odd:2,
        goals_bid_odd:2,
        ht_ft_bid_odd:2,
        both_teams_goals_bid_odd:2,
        final_bid_tip:"1",
        goals_bid_tip:"0-2",
        ht_ft_bid_tip:"1-1",
        both_teams_goals_bid_tip:"GG",
        tip_number:null
    }
},{//H B_W
    match:{
        id:1,
        code:1234,
        playground:"Rajko Mitic",
        dateTime:  "2019-08-10 15:00",
        tip_22:1.5,
        tip_2x:1.5,
        tip_21:1.5,
        tip_x2:1.5,
        tip_xx:1.5,
        tip_x1:1.5,
        tip_12:1.5,
        tip_1x:1.5,
        tip_11:1.5,
        tip2OrMore:1.5,
        tip03:1.5,
        tip01:1.5,
        GG3OrMore:1.5,
        GG:1.5,
        tip4OrMore:1.5,
        tip3OrMore:1.5,
        tip02:1.5,
        tip2OrMoreIP:1.5,
        club_home: "Crvena Zvezda",
        club_away:"Partizan",
        tipAway:1.5,
        tipX:1.5,
        tipHome:1.5,
        id_competition:3,
        id_week:7,
        home_logo:"https://ls.sportradar.com/ls/crest/big/5149.png",
        away_logo:"https://premierleague-static-files.s3.amazonaws.com/premierleague/badges/t216.png"

    },
    competition: {
        id: 3,
        name: 'Prva Srpska Liga',
    },
    week: {
        id: 5,
        name: 'Kolo 3'
    },
    results: {
        id:5,
        match_id:1,
        tip_22:null,
        tip_2x:null,
        tip_21:null,
        tip_x2:null,
        tip_xx:null,
        tip_x1:null,
        tip_12:null,
        tip_1x:null,
        tip_11:null,
        tip2OrMore:null,
        tip03:null,
        tip01:null,
        GG3OrMore:null,
        GG:null,
        tip4OrMore:null,
        tip3OrMore:null,
        tip02:null,
        tip2OrMoreIP:null,
        tipAway:null,
        tipX:null,
        tipHome:null,
        goals_home:2,
        goals_away:3,
        ht_home:1,
        ht_away:0,
        finished: true,
        current_min: 34,
    },
    ticket: {
        id:16,
        user_id:2,
        match_id:1,
        final_score:8,
        bid_score:8,
        final_bid_odd:2,
        goals_bid_odd:2,
        ht_ft_bid_odd:2,
        both_teams_goals_bid_odd:2,
        final_bid_tip:"1",
        goals_bid_tip:"0-2",
        ht_ft_bid_tip:"1-1",
        both_teams_goals_bid_tip:"GG",
        tip_number:null
    }
},{//H N
    match:{
        id:1,
        code:1234,
        playground:"Rajko Mitic",
        dateTime: "2018-12-2",
        tip_22:1.5,
        tip_2x:1.5,
        tip_21:1.5,
        tip_x2:1.5,
        tip_xx:1.5,
        tip_x1:1.5,
        tip_12:1.5,
        tip_1x:1.5,
        tip_11:1.5,
        tip2OrMore:1.5,
        tip03:1.5,
        tip01:1.5,
        GG3OrMore:1.5,
        GG:1.5,
        tip4OrMore:1.5,
        tip3OrMore:1.5,
        tip02:1.5,
        tip2OrMoreIP:1.5,
        club_home: "Crvena Zvezda",
        club_away:"Partizan",
        tipAway:1.5,
        tipX:1.5,
        tipHome:1.5,
        id_competition:3,
        id_week:7,
        home_logo:"https://ls.sportradar.com/ls/crest/big/5149.png",
        away_logo:"https://premierleague-static-files.s3.amazonaws.com/premierleague/badges/t216.png"

    },
    competition: {
        id: 3,
        name: 'Prva Srpska Liga',
    },
    week: {
        id: 5,
        name: 'Kolo 3'
    },
    results: {
        id:5,
        match_id:1,
        tip_22:null,
        tip_2x:null,
        tip_21:null,
        tip_x2:null,
        tip_xx:null,
        tip_x1:null,
        tip_12:null,
        tip_1x:null,
        tip_11:null,
        tip2OrMore:null,
        tip03:null,
        tip01:null,
        GG3OrMore:null,
        GG:null,
        tip4OrMore:null,
        tip3OrMore:null,
        tip02:null,
        tip2OrMoreIP:null,
        tipAway:null,
        tipX:null,
        tipHome:null,
        goals_home:2,
        goals_away:3,
        ht_home:1,
        ht_away:0,
        finished: true,
        current_min: 34,
    },
    ticket: null
},{//U B imamo
    match:{
        id:1,
        code:1234,
        playground:"Rajko Mitic",
        dateTime: "2019-08-13 15:00",
        tip_22:1.5,
        tip_2x:1.5,
        tip_21:1.5,
        tip_x2:1.5,
        tip_xx:1.5,
        tip_x1:1.5,
        tip_12:1.5,
        tip_1x:1.5,
        tip_11:1.5,
        tip2OrMore:1.5,
        tip03:1.5,
        tip01:1.5,
        GG3OrMore:1.5,
        GG:1.5,
        tip4OrMore:1.5,
        tip3OrMore:1.5,
        tip02:1.5,
        tip2OrMoreIP:1.5,
        club_home: "Crvena Zvezda",
        club_away:"Partizan",
        tipAway:1.5,
        tipX:1.5,
        tipHome:1.5,
        id_competition:3,
        id_week:7,
        home_logo:"https://ls.sportradar.com/ls/crest/big/5149.png",
        away_logo:"https://premierleague-static-files.s3.amazonaws.com/premierleague/badges/t216.png"

    },
    competition: {
        id: 3,
        name: 'Prva Srpska Liga',
    },
    week: {
        id: 5,
        name: 'Kolo 3'
    },
    results: null,
    ticket: {
        id:16,
        user_id:2,
        match_id:1,
        final_score:8,
        bid_score:8,
        final_bid_odd:2,
        goals_bid_odd:2,
        ht_ft_bid_odd:2,
        both_teams_goals_bid_odd:2,
        final_bid_tip:"1",
        goals_bid_tip:"0-2",
        ht_ft_bid_tip:"1-1",
        both_teams_goals_bid_tip:"GG",
        tip_number:null
    }
},{//H B_L
    match:{
        id:1,
        code:1234,
        playground:"Rajko Mitic",
        dateTime: "2018-12-2",
        tip_22:1.5,
        tip_2x:1.5,
        tip_21:1.5,
        tip_x2:1.5,
        tip_xx:1.5,
        tip_x1:1.5,
        tip_12:1.5,
        tip_1x:1.5,
        tip_11:1.5,
        tip2OrMore:1.5,
        tip03:1.5,
        tip01:1.5,
        GG3OrMore:1.5,
        GG:1.5,
        tip4OrMore:1.5,
        tip3OrMore:1.5,
        tip02:1.5,
        tip2OrMoreIP:1.5,
        club_home: "Crvena Zvezda",
        club_away:"Partizan",
        tipAway:1.5,
        tipX:1.5,
        tipHome:1.5,
        id_competition:3,
        id_week:7,
        home_logo:"https://ls.sportradar.com/ls/crest/big/5149.png",
        away_logo:"https://premierleague-static-files.s3.amazonaws.com/premierleague/badges/t216.png"

    },
    competition: {
        id: 3,
        name: 'Prva Srpska Liga',
    },
    week: {
        id: 5,
        name: 'Kolo 3'
    },
    results: {
        id:5,
        match_id:1,
        tip_22:null,
        tip_2x:null,
        tip_21:null,
        tip_x2:null,
        tip_xx:null,
        tip_x1:null,
        tip_12:null,
        tip_1x:null,
        tip_11:null,
        tip2OrMore:null,
        tip03:null,
        tip01:null,
        GG3OrMore:null,
        GG:null,
        tip4OrMore:null,
        tip3OrMore:null,
        tip02:null,
        tip2OrMoreIP:null,
        tipAway:null,
        tipX:null,
        tipHome:null,
        goals_home:2,
        goals_away:3,
        ht_home:1,
        ht_away:0,
        finished: true,
        current_min: 34,
    },
    ticket: {
        id:16,
        user_id:2,
        match_id:1,
        final_score:4,
        bid_score:8,
        final_bid_odd:0,
        goals_bid_odd:2,
        ht_ft_bid_odd:0,
        both_teams_goals_bid_odd:2,
        final_bid_tip:"1",
        goals_bid_tip:"0-2",
        ht_ft_bid_tip:"1-1",
        both_teams_goals_bid_tip:"GG",
        tip_number:null
    }
}]


object={
    state1:{//finished bidded lost
        competition: {
            id: 3,
                name: 'Prva Srpska Liga',
        },
        week: {
            id: 5,
                name: 'Kolo 3'
        },
        match: {
            id: 1,
                code: 1234,
                dateTime: "2019-08-13 15:00",
                playground: "Rajko Mitic",
                club_home: "Crvena Zvezda",
                home_logo: "https://ls.sportradar.com/ls/crest/big/5149.png",
                club_away: "Partizan",
                away_logo: "https://premierleague-static-files.s3.amazonaws.com/premierleague/badges/t216.png",
                game4_22: 1.5,
                game4_2x: 1.5,
                game4_21: 1.5,
                game4_x2: 1.5,
                game4_xx: 1.5,
                game4_x1: 1.5,
                game4_12: 1.5,
                game4_1x: 1.5,
                game4_11: 1.5,
                game3_gg3p: 1.5,
                game3_gg: 1.5,
                game2_4ft: 1.5,
                game2_3ft: 1.5,
                game2_2ft: 1.5,
                game2_2ht: 1.5,
                game2_3: 1.5,
                game2_2: 1.5,
                game2_1: 1.5,
                game1_2: 1.5,
                game1_x: 1.5,
                game1_1: 1.5,
                id_competition: 3,
                id_week: 7,
                upcoming:false
        },
        results: {
            id: 5,
                match_id: 1,
                game1_1: false,
                game1_x: false,
                game1_2: true,
                game2_1: false,
                game2_2: false,
                game2_3: false,
                game2_2ht: true,
                game2_2ft: true,
                game2_3ft: true,
                game2_4ft: true,
                game3_gg: true,
                game3_gg3p: true,
                game4_22: false,
                game4_2x: false,
                game4_21: false,
                game4_x2: false,
                game4_xx: false,
                game4_x1: false,
                game4_12: true,
                game4_1x: false,
                game4_11: false,
                goals_home_ht: 2,
                goals_away_ht: 0,
                goals_home_ft: 2,
                goals_away_ft: 3,
                finished: true,
                current_min: 90,
        },
        ticket: {
            id: 16,
                user_id: 2,
                match_id: 1,
                game1_tip: "2",
                game2_tip: "2",
                game3_tip: "gg",
                game4_tip: "22",
                game1_odd: 1.5,
                game2_odd: 0,
                game3_odd: 1.5,
                game4_odd: 0,
                final_score: 3,
                bid_score: 6
        }
    },
    state2:{//upcoming not bidded
        competition: {
            id: 3,
                name: 'Prva Srpska Liga',
        },
        week: {
            id: 5,
                name: 'Kolo 3'
        },
        match: {
            id: 1,
                code: 1234,
                dateTime: "2019-08-15 15:00",
                playground: "Rajko Mitic",
                club_home: "Crvena Zvezda",
                home_logo: "https://ls.sportradar.com/ls/crest/big/5149.png",
                club_away: "Partizan",
                away_logo: "https://premierleague-static-files.s3.amazonaws.com/premierleague/badges/t216.png",
                game4_22: 1.5,
                game4_2x: 1.5,
                game4_21: 1.5,
                game4_x2: 1.5,
                game4_xx: 1.5,
                game4_x1: 1.5,
                game4_12: 1.5,
                game4_1x: 1.5,
                game4_11: 1.5,
                game3_gg3p: 1.5,
                game3_gg: 1.5,
                game2_4ft: 1.5,
                game2_3ft: 1.5,
                game2_2ft: 1.5,
                game2_2ht: 1.5,
                game2_3: 1.5,
                game2_2: 1.5,
                game2_1: 1.5,
                game1_2: 1.5,
                game1_x: 1.5,
                game1_1: 1.5,
                id_competition: 3,
                id_week: 7,
                upcoming:true
        },
        results: {
            id: 5,
                match_id: 1,
                game1_1: false,
                game1_x: false,
                game1_2: false,
                game2_1: false,
                game2_2: false,
                game2_3: false,
                game2_2ht: false,
                game2_2ft: false,
                game2_3ft: false,
                game2_4ft: false,
                game3_gg: false,
                game3_gg3p: false,
                game4_22: false,
                game4_2x: false,
                game4_21: false,
                game4_x2: false,
                game4_xx: false,
                game4_x1: false,
                game4_12: false,
                game4_1x: false,
                game4_11: false,
                goals_home_ht: 0,
                goals_away_ht: 0,
                goals_home_ft: 0,
                goals_away_ft: 0,
                finished: false,
                current_min: 0,
        },
        ticket: {
            id: 16,
                user_id: 2,
                match_id: 1,
                game1_tip: null,
                game2_tip: null,
                game3_tip: null,
                game4_tip: null,
                game1_odd: 0,
                game2_odd: 0,
                game3_odd: 0,
                game4_odd: 0,
                final_score: 0,
                bid_score: 0
        }
    },
    state3:{//upcoming bidded
        competition: {
            id: 3,
                name: 'Prva Srpska Liga',
        },
        week: {
            id: 5,
                name: 'Kolo 3'
        },
        match: {
            id: 1,
                code: 1234,
                dateTime: "2019-08-15 15:00",
                playground: "Rajko Mitic",
                club_home: "Crvena Zvezda",
                home_logo: "https://ls.sportradar.com/ls/crest/big/5149.png",
                club_away: "Partizan",
                away_logo: "https://premierleague-static-files.s3.amazonaws.com/premierleague/badges/t216.png",
                game4_22: 1.5,
                game4_2x: 1.5,
                game4_21: 1.5,
                game4_x2: 1.5,
                game4_xx: 1.5,
                game4_x1: 1.5,
                game4_12: 1.5,
                game4_1x: 1.5,
                game4_11: 1.5,
                game3_gg3p: 1.5,
                game3_gg: 1.5,
                game2_4ft: 1.5,
                game2_3ft: 1.5,
                game2_2ft: 1.5,
                game2_2ht: 1.5,
                game2_3: 1.5,
                game2_2: 1.5,
                game2_1: 1.5,
                game1_2: 1.5,
                game1_x: 1.5,
                game1_1: 1.5,
                id_competition: 3,
                id_week: 7,
                upcoming:true
        },
        results: {
            id: 5,
                match_id: 1,
                game1_1: false,
                game1_x: false,
                game1_2: false,
                game2_1: false,
                game2_2: false,
                game2_3: false,
                game2_2ht: false,
                game2_2ft: false,
                game2_3ft: false,
                game2_4ft: false,
                game3_gg: false,
                game3_gg3p: false,
                game4_22: false,
                game4_2x: false,
                game4_21: false,
                game4_x2: false,
                game4_xx: false,
                game4_x1: false,
                game4_12: false,
                game4_1x: false,
                game4_11: false,
                goals_home_ht: 0,
                goals_away_ht: 0,
                goals_home_ft: 0,
                goals_away_ft: 0,
                finished: false,
                current_min: 0,
        },
        ticket: {
            id: 16,
                user_id: 2,
                match_id: 1,
                game1_tip: "2",
                game2_tip: "2",
                game3_tip: "gg",
                game4_tip: "22",
                game1_odd: 1.5,
                game2_odd: 1.5,
                game3_odd: 1.5,
                game4_odd: 1.5,
                final_score: 0,
                bid_score: 6
        }
    },
    state4:{//finished bidded won
        competition: {
            id: 3,
                name: 'Prva Srpska Liga',
        },
        week: {
            id: 5,
                name: 'Kolo 3'
        },
        match: {
            id: 1,
                code: 1234,
                dateTime: "2019-08-13 15:00",
                playground: "Rajko Mitic",
                club_home: "Crvena Zvezda",
                home_logo: "https://ls.sportradar.com/ls/crest/big/5149.png",
                club_away: "Partizan",
                away_logo: "https://premierleague-static-files.s3.amazonaws.com/premierleague/badges/t216.png",
                game4_22: 1.5,
                game4_2x: 1.5,
                game4_21: 1.5,
                game4_x2: 1.5,
                game4_xx: 1.5,
                game4_x1: 1.5,
                game4_12: 1.5,
                game4_1x: 1.5,
                game4_11: 1.5,
                game3_gg3p: 1.5,
                game3_gg: 1.5,
                game2_4ft: 1.5,
                game2_3ft: 1.5,
                game2_2ft: 1.5,
                game2_2ht: 1.5,
                game2_3: 1.5,
                game2_2: 1.5,
                game2_1: 1.5,
                game1_2: 1.5,
                game1_x: 1.5,
                game1_1: 1.5,
                id_competition: 3,
                id_week: 7,
                upcoming:false
        },
        results: {
            id: 5,
                match_id: 1,
                game1_1: true,
                game1_x: false,
                game1_2: false,
                game2_1: true,
                game2_2: true,
                game2_3: true,
                game2_2ht: false,
                game2_2ft: true,
                game2_3ft: false,
                game2_4ft: false,
                game3_gg: true,
                game3_gg3p: false,
                game4_22: false,
                game4_2x: false,
                game4_21: false,
                game4_x2: false,
                game4_xx: true,
                game4_x1: false,
                game4_12: false,
                game4_1x: false,
                game4_11: false,
                goals_home_ht: 1,
                goals_away_ht: 1,
                goals_home_ft: 0,
                goals_away_ft: 0,
                finished: true,
                current_min: 90,
        },
        ticket: {
            id: 16,
                user_id: 2,
                match_id: 1,
                game1_tip: "x",
                game2_tip: "2",
                game3_tip: "gg",
                game4_tip: "xx",
                game1_odd: 1.5,
                game2_odd: 1.5,
                game3_odd: 1.5,
                game4_odd: 1.5,
                final_score: 6,
                bid_score: 6
        }
    },
    state5:{//live not bidded
        competition: {
            id: 3,
                name: 'Prva Srpska Liga',
        },
        week: {
            id: 5,
                name: 'Kolo 3'
        },
        match: {
            id: 1,
                code: 1234,
                dateTime: "2019-08-14 14:00",
                playground: "Rajko Mitic",
                club_home: "Crvena Zvezda",
                home_logo: "https://ls.sportradar.com/ls/crest/big/5149.png",
                club_away: "Partizan",
                away_logo: "https://premierleague-static-files.s3.amazonaws.com/premierleague/badges/t216.png",
                game4_22: 1.5,
                game4_2x: 1.5,
                game4_21: 1.5,
                game4_x2: 1.5,
                game4_xx: 1.5,
                game4_x1: 1.5,
                game4_12: 1.5,
                game4_1x: 1.5,
                game4_11: 1.5,
                game3_gg3p: 1.5,
                game3_gg: 1.5,
                game2_4ft: 1.5,
                game2_3ft: 1.5,
                game2_2ft: 1.5,
                game2_2ht: 1.5,
                game2_3: 1.5,
                game2_2: 1.5,
                game2_1: 1.5,
                game1_2: 1.5,
                game1_x: 1.5,
                game1_1: 1.5,
                id_competition: 3,
                id_week: 7,
                upcoming:false
        },
        results: {
            id: 5,
                match_id: 1,
                game1_1: false,
                game1_x: false,
                game1_2: false,
                game2_1: false,
                game2_2: false,
                game2_3: false,
                game2_2ht: false,
                game2_2ft: false,
                game2_3ft: false,
                game2_4ft: false,
                game3_gg: false,
                game3_gg3p: false,
                game4_22: false,
                game4_2x: false,
                game4_21: false,
                game4_x2: false,
                game4_xx: false,
                game4_x1: false,
                game4_12: false,
                game4_1x: false,
                game4_11: false,
                goals_home_ht: 0,
                goals_away_ht: 0,
                goals_home_ft: null,
                goals_away_ft: null,
                finished: false,
                current_min: 8,
        },
        ticket: {
            id: 16,
                user_id: 2,
                match_id: 1,
                game1_tip: null,
                game2_tip: null,
                game3_tip: null,
                game4_tip: null,
                game1_odd: 0,
                game2_odd: 0,
                game3_odd: 0,
                game4_odd: 0,
                final_score: 0,
                bid_score: 0
        }
    },
    state6:{// live bidded
        competition: {
            id: 3,
                name: 'Prva Srpska Liga',
        },
        week: {
            id: 5,
                name: 'Kolo 3'
        },
        match: {
            id: 1,
                code: 1234,
                dateTime: "2019-08-13 14:00",
                playground: "Rajko Mitic",
                club_home: "Crvena Zvezda",
                home_logo: "https://ls.sportradar.com/ls/crest/big/5149.png",
                club_away: "Partizan",
                away_logo: "https://premierleague-static-files.s3.amazonaws.com/premierleague/badges/t216.png",
                game4_22: 1.5,
                game4_2x: 1.5,
                game4_21: 1.5,
                game4_x2: 1.5,
                game4_xx: 1.5,
                game4_x1: 1.5,
                game4_12: 1.5,
                game4_1x: 1.5,
                game4_11: 1.5,
                game3_gg3p: 1.5,
                game3_gg: 1.5,
                game2_4ft: 1.5,
                game2_3ft: 1.5,
                game2_2ft: 1.5,
                game2_2ht: 1.5,
                game2_3: 1.5,
                game2_2: 1.5,
                game2_1: 1.5,
                game1_2: 1.5,
                game1_x: 1.5,
                game1_1: 1.5,
                id_competition: 3,
                id_week: 7,
                upcoming:false
        },
        results: {
            id: 5,
                match_id: 1,
                game1_1: false,
                game1_x: false,
                game1_2: false,
                game2_1: false,
                game2_2: false,
                game2_3: false,
                game2_2ht: false,
                game2_2ft: false,
                game2_3ft: false,
                game2_4ft: false,
                game3_gg: false,
                game3_gg3p: false,
                game4_22: false,
                game4_2x: false,
                game4_21: false,
                game4_x2: false,
                game4_xx: false,
                game4_x1: false,
                game4_12: false,
                game4_1x: false,
                game4_11: false,
                goals_home_ht: 2,
                goals_away_ht: 0,
                goals_home_ft: null,
                goals_away_ft: null,
                finished: false,
                current_min: 64,
        },
        ticket: {
            id: 16,
                user_id: 2,
                match_id: 1,
                game1_tip: "2",
                game2_tip: "2",
                game3_tip: "gg",
                game4_tip: "22",
                game1_odd: 1.5,
                game2_odd: 1.5,
                game3_odd: 1.5,
                game4_odd: 1.5,
                final_score: 0,
                bid_score: 6
        }
    },
    state7:{// finished not bidded
        competition: {
            id: 3,
                name: 'Prva Srpska Liga',
        },
        week: {
            id: 5,
                name: 'Kolo 3'
        },
        match: {
            id: 1,
                code: 1234,
                dateTime: "2019-08-13 15:00",
                playground: "Rajko Mitic",
                club_home: "Crvena Zvezda",
                home_logo: "https://ls.sportradar.com/ls/crest/big/5149.png",
                club_away: "Partizan",
                away_logo: "https://premierleague-static-files.s3.amazonaws.com/premierleague/badges/t216.png",
                game4_22: 1.5,
                game4_2x: 1.5,
                game4_21: 1.5,
                game4_x2: 1.5,
                game4_xx: 1.5,
                game4_x1: 1.5,
                game4_12: 1.5,
                game4_1x: 1.5,
                game4_11: 1.5,
                game3_gg3p: 1.5,
                game3_gg: 1.5,
                game2_4ft: 1.5,
                game2_3ft: 1.5,
                game2_2ft: 1.5,
                game2_2ht: 1.5,
                game2_3: 1.5,
                game2_2: 1.5,
                game2_1: 1.5,
                game1_2: 1.5,
                game1_x: 1.5,
                game1_1: 1.5,
                id_competition: 3,
                id_week: 7,
                upcoming:false
        },
        results: {
            id: 5,
                match_id: 1,
                game1_1: false,
                game1_x: true,
                game1_2: false,
                game2_1: false,
                game2_2: false,
                game2_3: false,
                game2_2ht: true,
                game2_2ft: true,
                game2_3ft: false,
                game2_4ft: false,
                game3_gg: true,
                game3_gg3p: true,
                game4_22: false,
                game4_2x: false,
                game4_21: false,
                game4_x2: false,
                game4_xx: true,
                game4_x1: false,
                game4_12: false,
                game4_1x: false,
                game4_11: false,
                goals_home_ht: 1,
                goals_away_ht: 1,
                goals_home_ft: 2,
                goals_away_ft: 2,
                finished: true,
                current_min: 90,
        },
        ticket: {
            id: 16,
                user_id: 2,
                match_id: 1,
                game1_tip: null,
                game2_tip: null,
                game3_tip: null,
                game4_tip: null,
                game1_odd: 0,
                game2_odd: 0,
                game3_odd: 0,
                game4_odd: 0,
                final_score: 0,
                bid_score: 0
        }
    }
}