data = [{//U N imamo
    match:{
        id:1,
        code:1234,
        dateTime: "2019-08-14 21:00",
        playground:"Rajko Mitic",
        tip_22:1.5,
        tip_2x:1.5,
        tip_21:1.5,
        tip_x2:1.5,
        tip_xx:1.5,
        tip_x1:1.5,
        tip_12:1.5,
        tip_1x:1.5,
        tip_11:1.5,
        tip2OrMore:1.5,
        tip03:1.5,
        tip01:1.5,
        GG3OrMore:1.5,
        GG:1.5,
        tip4OrMore:1.5,
        tip3OrMore:1.5,
        tip02:1.5,
        tip2OrMoreIP:1.5,
        club_home: "Crvena Zvezda",
        club_away:"Partizan",
        tipAway:1.5,
        tipX:1.5,
        tipHome:1.5,
        id_competition:3,
        id_week:7,
        home_logo:"https://ls.sportradar.com/ls/crest/big/5149.png",
        away_logo:"https://premierleague-static-files.s3.amazonaws.com/premierleague/badges/t216.png"

    },
    competition: {
        id: 3,
        name: 'Prva Srpska Liga',
    },
    week: {
        id: 5,
        name: 'Kolo 3'
    },
    results: null,
    ticket: null
},{//L N
    match:{
        id:1,
        code:1234,
        playground:"Rajko Mitic",
        dateTime: "2019-08-13 15:00",
        tip_22:1.5,
        tip_2x:1.5,
        tip_21:1.5,
        tip_x2:1.5,
        tip_xx:1.5,
        tip_x1:1.5,
        tip_12:1.5,
        tip_1x:1.5,
        tip_11:1.5,
        tip2OrMore:1.5,
        tip03:1.5,
        tip01:1.5,
        GG3OrMore:1.5,
        GG:1.5,
        tip4OrMore:1.5,
        tip3OrMore:1.5,
        tip02:1.5,
        tip2OrMoreIP:1.5,
        club_home: "Crvena Zvezda",
        club_away:"Partizan",
        tipAway:1.5,
        tipX:1.5,
        tipHome:1.5,
        id_competition:3,
        id_week:7,
        home_logo:"https://ls.sportradar.com/ls/crest/big/5149.png",
        away_logo:"https://premierleague-static-files.s3.amazonaws.com/premierleague/badges/t216.png"

    },
    competition: {
        id: 3,
        name: 'Prva Srpska Liga',
    },
    week: {
        id: 5,
        name: 'Kolo 3'
    },
    results: {
        id:5,
        match_id:1,
        tip_22:null,
        tip_2x:null,
        tip_21:null,
        tip_x2:null,
        tip_xx:null,
        tip_x1:null,
        tip_12:null,
        tip_1x:null,
        tip_11:null,
        tip2OrMore:null,
        tip03:null,
        tip01:null,
        GG3OrMore:null,
        GG:null,
        tip4OrMore:null,
        tip3OrMore:null,
        tip02:null,
        tip2OrMoreIP:null,
        tipAway:null,
        tipX:null,
        tipHome:null,
        goals_home:2,
        goals_away:3,
        ht_home:1,
        ht_away:0,
        finished: false,
        current_min: 34,
    },
    ticket: null
},{//L B
    match:{
        id:1,
        code:1234,
        playground:"Rajko Mitic",
        dateTime: "2019-08-13 15:00",
        tip_22:1.5,
        tip_2x:1.5,
        tip_21:1.5,
        tip_x2:1.5,
        tip_xx:1.5,
        tip_x1:1.5,
        tip_12:1.5,
        tip_1x:1.5,
        tip_11:1.5,
        tip2OrMore:1.5,
        tip03:1.5,
        tip01:1.5,
        GG3OrMore:1.5,
        GG:1.5,
        tip4OrMore:1.5,
        tip3OrMore:1.5,
        tip02:1.5,
        tip2OrMoreIP:1.5,
        club_home: "Crvena Zvezda",
        club_away:"Partizan",
        tipAway:1.5,
        tipX:1.5,
        tipHome:1.5,
        id_competition:3,
        id_week:7,
        home_logo:"https://ls.sportradar.com/ls/crest/big/5149.png",
        away_logo:"https://premierleague-static-files.s3.amazonaws.com/premierleague/badges/t216.png"

    },
    competition: {
        id: 3,
        name: 'Prva Srpska Liga',
    },
    week: {
        id: 5,
        name: 'Kolo 3'
    },
    results: {
        id:5,
        match_id:1,
        tip_22:null,
        tip_2x:null,
        tip_21:null,
        tip_x2:null,
        tip_xx:null,
        tip_x1:null,
        tip_12:null,
        tip_1x:null,
        tip_11:null,
        tip2OrMore:null,
        tip03:null,
        tip01:null,
        GG3OrMore:null,
        GG:null,
        tip4OrMore:null,
        tip3OrMore:null,
        tip02:null,
        tip2OrMoreIP:null,
        tipAway:null,
        tipX:null,
        tipHome:null,
        goals_home:2,
        goals_away:3,
        ht_home:1,
        ht_away:0,
        finished: false,
        current_min: 34,
    },
    ticket: {
        id:16,
        user_id:2,
        match_id:1,
        final_score:8,
        bid_score:8,
        final_bid_odd:2,
        goals_bid_odd:2,
        ht_ft_bid_odd:2,
        both_teams_goals_bid_odd:2,
        final_bid_tip:"1",
        goals_bid_tip:"0-2",
        ht_ft_bid_tip:"1-1",
        both_teams_goals_bid_tip:"GG",
        tip_number:null
    }
},{//H B_W
    match:{
        id:1,
        code:1234,
        playground:"Rajko Mitic",
        dateTime:  "2019-08-10 15:00",
        tip_22:1.5,
        tip_2x:1.5,
        tip_21:1.5,
        tip_x2:1.5,
        tip_xx:1.5,
        tip_x1:1.5,
        tip_12:1.5,
        tip_1x:1.5,
        tip_11:1.5,
        tip2OrMore:1.5,
        tip03:1.5,
        tip01:1.5,
        GG3OrMore:1.5,
        GG:1.5,
        tip4OrMore:1.5,
        tip3OrMore:1.5,
        tip02:1.5,
        tip2OrMoreIP:1.5,
        club_home: "Crvena Zvezda",
        club_away:"Partizan",
        tipAway:1.5,
        tipX:1.5,
        tipHome:1.5,
        id_competition:3,
        id_week:7,
        home_logo:"https://ls.sportradar.com/ls/crest/big/5149.png",
        away_logo:"https://premierleague-static-files.s3.amazonaws.com/premierleague/badges/t216.png"

    },
    competition: {
        id: 3,
        name: 'Prva Srpska Liga',
    },
    week: {
        id: 5,
        name: 'Kolo 3'
    },
    results: {
        id:5,
        match_id:1,
        tip_22:null,
        tip_2x:null,
        tip_21:null,
        tip_x2:null,
        tip_xx:null,
        tip_x1:null,
        tip_12:null,
        tip_1x:null,
        tip_11:null,
        tip2OrMore:null,
        tip03:null,
        tip01:null,
        GG3OrMore:null,
        GG:null,
        tip4OrMore:null,
        tip3OrMore:null,
        tip02:null,
        tip2OrMoreIP:null,
        tipAway:null,
        tipX:null,
        tipHome:null,
        goals_home:2,
        goals_away:3,
        ht_home:1,
        ht_away:0,
        finished: true,
        current_min: 34,
    },
    ticket: {
        id:16,
        user_id:2,
        match_id:1,
        final_score:8,
        bid_score:8,
        final_bid_odd:2,
        goals_bid_odd:2,
        ht_ft_bid_odd:2,
        both_teams_goals_bid_odd:2,
        final_bid_tip:"1",
        goals_bid_tip:"0-2",
        ht_ft_bid_tip:"1-1",
        both_teams_goals_bid_tip:"GG",
        tip_number:null
    }
},{//H N
    match:{
        id:1,
        code:1234,
        playground:"Rajko Mitic",
        dateTime: "2018-12-2",
        tip_22:1.5,
        tip_2x:1.5,
        tip_21:1.5,
        tip_x2:1.5,
        tip_xx:1.5,
        tip_x1:1.5,
        tip_12:1.5,
        tip_1x:1.5,
        tip_11:1.5,
        tip2OrMore:1.5,
        tip03:1.5,
        tip01:1.5,
        GG3OrMore:1.5,
        GG:1.5,
        tip4OrMore:1.5,
        tip3OrMore:1.5,
        tip02:1.5,
        tip2OrMoreIP:1.5,
        club_home: "Crvena Zvezda",
        club_away:"Partizan",
        tipAway:1.5,
        tipX:1.5,
        tipHome:1.5,
        id_competition:3,
        id_week:7,
        home_logo:"https://ls.sportradar.com/ls/crest/big/5149.png",
        away_logo:"https://premierleague-static-files.s3.amazonaws.com/premierleague/badges/t216.png"

    },
    competition: {
        id: 3,
        name: 'Prva Srpska Liga',
    },
    week: {
        id: 5,
        name: 'Kolo 3'
    },
    results: {
        id:5,
        match_id:1,
        tip_22:null,
        tip_2x:null,
        tip_21:null,
        tip_x2:null,
        tip_xx:null,
        tip_x1:null,
        tip_12:null,
        tip_1x:null,
        tip_11:null,
        tip2OrMore:null,
        tip03:null,
        tip01:null,
        GG3OrMore:null,
        GG:null,
        tip4OrMore:null,
        tip3OrMore:null,
        tip02:null,
        tip2OrMoreIP:null,
        tipAway:null,
        tipX:null,
        tipHome:null,
        goals_home:2,
        goals_away:3,
        ht_home:1,
        ht_away:0,
        finished: true,
        current_min: 34,
    },
    ticket: null
},{//U B imamo
    match:{
        id:1,
        code:1234,
        playground:"Rajko Mitic",
        dateTime: "2019-08-13 15:00",
        tip_22:1.5,
        tip_2x:1.5,
        tip_21:1.5,
        tip_x2:1.5,
        tip_xx:1.5,
        tip_x1:1.5,
        tip_12:1.5,
        tip_1x:1.5,
        tip_11:1.5,
        tip2OrMore:1.5,
        tip03:1.5,
        tip01:1.5,
        GG3OrMore:1.5,
        GG:1.5,
        tip4OrMore:1.5,
        tip3OrMore:1.5,
        tip02:1.5,
        tip2OrMoreIP:1.5,
        club_home: "Crvena Zvezda",
        club_away:"Partizan",
        tipAway:1.5,
        tipX:1.5,
        tipHome:1.5,
        id_competition:3,
        id_week:7,
        home_logo:"https://ls.sportradar.com/ls/crest/big/5149.png",
        away_logo:"https://premierleague-static-files.s3.amazonaws.com/premierleague/badges/t216.png"

    },
    competition: {
        id: 3,
        name: 'Prva Srpska Liga',
    },
    week: {
        id: 5,
        name: 'Kolo 3'
    },
    results: null,
    ticket: {
        id:16,
        user_id:2,
        match_id:1,
        final_score:8,
        bid_score:8,
        final_bid_odd:2,
        goals_bid_odd:2,
        ht_ft_bid_odd:2,
        both_teams_goals_bid_odd:2,
        final_bid_tip:"1",
        goals_bid_tip:"0-2",
        ht_ft_bid_tip:"1-1",
        both_teams_goals_bid_tip:"GG",
        tip_number:null
    }
},{//H B_L
    match:{
        id:1,
        code:1234,
        playground:"Rajko Mitic",
        dateTime: "2018-12-2",
        tip_22:1.5,
        tip_2x:1.5,
        tip_21:1.5,
        tip_x2:1.5,
        tip_xx:1.5,
        tip_x1:1.5,
        tip_12:1.5,
        tip_1x:1.5,
        tip_11:1.5,
        tip2OrMore:1.5,
        tip03:1.5,
        tip01:1.5,
        GG3OrMore:1.5,
        GG:1.5,
        tip4OrMore:1.5,
        tip3OrMore:1.5,
        tip02:1.5,
        tip2OrMoreIP:1.5,
        club_home: "Crvena Zvezda",
        club_away:"Partizan",
        tipAway:1.5,
        tipX:1.5,
        tipHome:1.5,
        id_competition:3,
        id_week:7,
        home_logo:"https://ls.sportradar.com/ls/crest/big/5149.png",
        away_logo:"https://premierleague-static-files.s3.amazonaws.com/premierleague/badges/t216.png"

    },
    competition: {
        id: 3,
        name: 'Prva Srpska Liga',
    },
    week: {
        id: 5,
        name: 'Kolo 3'
    },
    results: {
        id:5,
        match_id:1,
        tip_22:null,
        tip_2x:null,
        tip_21:null,
        tip_x2:null,
        tip_xx:null,
        tip_x1:null,
        tip_12:null,
        tip_1x:null,
        tip_11:null,
        tip2OrMore:null,
        tip03:null,
        tip01:null,
        GG3OrMore:null,
        GG:null,
        tip4OrMore:null,
        tip3OrMore:null,
        tip02:null,
        tip2OrMoreIP:null,
        tipAway:null,
        tipX:null,
        tipHome:null,
        goals_home:2,
        goals_away:3,
        ht_home:1,
        ht_away:0,
        finished: true,
        current_min: 34,
    },
    ticket: {
        id:16,
        user_id:2,
        match_id:1,
        final_score:4,
        bid_score:8,
        final_bid_odd:0,
        goals_bid_odd:2,
        ht_ft_bid_odd:0,
        both_teams_goals_bid_odd:2,
        final_bid_tip:"1",
        goals_bid_tip:"0-2",
        ht_ft_bid_tip:"1-1",
        both_teams_goals_bid_tip:"GG",
        tip_number:null
    }
}]